import { Inter } from 'next/font/google';
import './globals.css'; // Perbarui jalur impor untuk global.css
import Header from '../components/Header';
import Footer from '../components/Footer';
import { MantineProvider } from '@mantine/core';
import '@mantine/carousel/styles.css';


const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider>
          <Header />
          <main>        
            {children}
          </main>
        </MantineProvider>
        <Footer />
      </body>
    </html>
  );
}
